### ISSUE TITLE
Not sure what to title

### ISSUE THREAD

**Issue by throwawaya609** [ShmuelLa/Evil-Twin#1]
![image](https://user-images.githubusercontent.com/109557965/184044184-6874e8d6-20b7-4cad-ae92-9e2e1cba2d90.png)

**Comment by ShmuelLa** [comment]
Hi, did you try to run the code with root? 
And also did you install all dependencies?

**Comment by throwawaya609** [comment]
I got it to work by adding python before main.py should've done that in the first place, lol
